package Vista;

import Controlador.ControladorMascotas;
import java.util.Date;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class Registrar_Mascota extends javax.swing.JInternalFrame {

    private DefaultTableModel modeloTabla;
    

    public Registrar_Mascota() {
        initComponents();

        // Inicializar el modelo de la tabla con los nombres de las columnas
        modeloTabla = new DefaultTableModel(new String[]{
            "Código", "Nombre", "Especie", "Raza", "Características",
            "Sexo", "Castrado", "Fecha Nacimiento", "Peso", "Propietario", "Num. Propietario"
        }, 0);
        tableDatosMascota.setModel(modeloTabla); // Asignar el modelo a la tabla

// Configurar el ComboBox de Sexo
        cboxSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"MACHO", "HEMBRA"}));

// Configurar el ComboBox de Castrado
        cboxCastrado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"SI", "NO"}));

    }

    public void mostrarMensaje(String mensaje) {
        javax.swing.JOptionPane.showMessageDialog(this, mensaje);
    }

    // Getters para los botones
    public javax.swing.JButton getBtnGuardar() {
        return btnGuardar;
    }

    public javax.swing.JButton getBtnEditar() {
        return btnEditar;
    }

    public javax.swing.JButton getBtnEliminar() {
        return btnEliminar;
    }

    public javax.swing.JButton getBtnRefrescar() {
        return btnRefrescar;
    }

    // Getters para la tabla
    public javax.swing.JTable getTableDatosMascota() {
        return tableDatosMascota;
    }

    // Getters para los campos de texto
    public javax.swing.JTextField getTxtCodigo() {
        return txtCodigo;
    }

    public javax.swing.JTextField getTxtNombre() {
        return txtNombre;
    }

    public javax.swing.JTextField getTxtEspecie() {
        return txtEspecie;
    }

    public javax.swing.JTextField getTxtRaza() {
        return txtRaza;
    }

    public javax.swing.JTextField getTxtPeso() {
        return txtPeso;
    }

    public javax.swing.JTextField getTxtPropietario() {
        return txtPropietario; // Supongo que este campo es el de propietario
    }

    public javax.swing.JTextField getTxtNumPropietario() {
        return txtNumPropietario; // Supongo que este campo es el de número de propietario
    }

    // Getters para el JTextArea de características
    public javax.swing.JTextArea getJtxtCaracteristicas() {
        return jtxtCaracteristicas;
    }

    // Getters para los JComboBox
    public javax.swing.JComboBox<String> getCboxSexo() {
        return cboxSexo;
    }

    public javax.swing.JComboBox<String> getCboxCastrado() {
        return cboxCastrado;
    }

    // Getter para el JDateChooser
    public com.toedter.calendar.JDateChooser getDateNacimiento() {
        return dateNacimiento;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableDatosMascota = new javax.swing.JTable();
        panelMascota = new javax.swing.JPanel();
        lblCodigo = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblEspecie = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblFechaNac = new javax.swing.JLabel();
        lblCastrado = new javax.swing.JLabel();
        lblSexo = new javax.swing.JLabel();
        lblPeso = new javax.swing.JLabel();
        lblRaza = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtEspecie = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtxtCaracteristicas = new javax.swing.JTextArea();
        cboxCastrado = new javax.swing.JComboBox<>();
        txtPeso = new javax.swing.JTextField();
        dateNacimiento = new com.toedter.calendar.JDateChooser();
        txtRaza = new javax.swing.JTextField();
        cboxSexo = new javax.swing.JComboBox<>();
        JPanelBotonesMasc = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnRefrescar = new javax.swing.JButton();
        lblNumero = new javax.swing.JLabel();
        txtPropietario = new javax.swing.JTextField();
        lblPropietario1 = new javax.swing.JLabel();
        txtNumPropietario = new javax.swing.JTextField();

        setClosable(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("REGSITRO MASCOTAS");

        tableDatosMascota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableDatosMascota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableDatosMascotaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableDatosMascota);

        panelMascota.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATOS DE LA MASCOTA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(204, 0, 0))); // NOI18N
        panelMascota.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCodigo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCodigo.setText("CODIGO DE MASCOTA:");
        panelMascota.add(lblCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 28, -1, -1));

        lblNombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNombre.setText("NOMBRE:");
        panelMascota.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 60, -1, -1));

        lblEspecie.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEspecie.setText("ESPECIE:");
        panelMascota.add(lblEspecie, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 92, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("CARACTERISTICAS:");
        panelMascota.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 136, -1, -1));

        lblFechaNac.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblFechaNac.setText("FECHA DE NACIMIENTO:");
        panelMascota.add(lblFechaNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(547, 25, -1, -1));

        lblCastrado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCastrado.setText("CASTRADO:");
        panelMascota.add(lblCastrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 263, -1, -1));

        lblSexo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSexo.setText("SEXO:");
        panelMascota.add(lblSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(546, 95, -1, -1));

        lblPeso.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPeso.setText("PESO:");
        panelMascota.add(lblPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(547, 57, -1, -1));

        lblRaza.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblRaza.setText("RAZA:");
        panelMascota.add(lblRaza, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 225, -1, -1));

        txtCodigo.setEditable(false);
        txtCodigo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        panelMascota.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 22, 137, -1));

        txtNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });
        panelMascota.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 54, 237, -1));

        txtEspecie.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtEspecie.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEspecieKeyTyped(evt);
            }
        });
        panelMascota.add(txtEspecie, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 92, 237, -1));

        jtxtCaracteristicas.setColumns(20);
        jtxtCaracteristicas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtxtCaracteristicas.setRows(5);
        jtxtCaracteristicas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtCaracteristicasKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(jtxtCaracteristicas);

        panelMascota.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 136, 306, 74));

        cboxCastrado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cboxCastrado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelMascota.add(cboxCastrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 260, 157, -1));

        txtPeso.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        panelMascota.add(txtPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(593, 54, 163, -1));

        dateNacimiento.setForeground(new java.awt.Color(0, 0, 204));
        dateNacimiento.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        panelMascota.add(dateNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(722, 22, 168, -1));

        txtRaza.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtRaza.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRazaKeyTyped(evt);
            }
        });
        panelMascota.add(txtRaza, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 222, 157, -1));

        cboxSexo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cboxSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelMascota.add(cboxSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(593, 92, 162, -1));

        JPanelBotonesMasc.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        JPanelBotonesMasc.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGuardar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        JPanelBotonesMasc.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        btnEditar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEditar.setText("EDITAR");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        JPanelBotonesMasc.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 105, -1));

        btnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        JPanelBotonesMasc.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, -1, -1));

        btnRefrescar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRefrescar.setText("ACTUALIZAR");
        btnRefrescar.setPreferredSize(new java.awt.Dimension(35, 35));
        btnRefrescar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefrescarActionPerformed(evt);
            }
        });
        JPanelBotonesMasc.add(btnRefrescar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 105, 21));

        panelMascota.add(JPanelBotonesMasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, 530, 40));

        lblNumero.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNumero.setText("NUM_PROPIETARIO:");
        panelMascota.add(lblNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 180, -1, -1));
        panelMascota.add(txtPropietario, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 140, 250, -1));

        lblPropietario1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPropietario1.setText("PROPIETARIO:");
        panelMascota.add(lblPropietario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, -1, -1));

        txtNumPropietario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        panelMascota.add(txtNumPropietario, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 180, 210, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelMascota, javax.swing.GroupLayout.DEFAULT_SIZE, 934, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(344, 344, 344)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelMascota, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableDatosMascotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableDatosMascotaMouseClicked
  int filaSeleccionada = tableDatosMascota.getSelectedRow();  // Accede directamente a la tabla
    if (filaSeleccionada != -1) {
        txtCodigo.setText(tableDatosMascota.getValueAt(filaSeleccionada, 0).toString());
        txtNombre.setText(tableDatosMascota.getValueAt(filaSeleccionada, 1).toString());
        txtEspecie.setText(tableDatosMascota.getValueAt(filaSeleccionada, 2).toString());
        txtRaza.setText(tableDatosMascota.getValueAt(filaSeleccionada, 3).toString());
        jtxtCaracteristicas.setText(tableDatosMascota.getValueAt(filaSeleccionada, 4).toString());
        cboxSexo.setSelectedItem(tableDatosMascota.getValueAt(filaSeleccionada, 5).toString());
        cboxCastrado.setSelectedItem(tableDatosMascota.getValueAt(filaSeleccionada, 6).toString());

        // Convertir y asignar la fecha
        Date fecha = (Date) tableDatosMascota.getValueAt(filaSeleccionada, 7);
        dateNacimiento.setDate(fecha);  // Asignar la fecha de nacimiento

        txtPeso.setText(tableDatosMascota.getValueAt(filaSeleccionada, 8).toString());
        txtPropietario.setText(tableDatosMascota.getValueAt(filaSeleccionada, 9).toString());
        txtNumPropietario.setText(tableDatosMascota.getValueAt(filaSeleccionada, 10).toString());
    }
    }//GEN-LAST:event_tableDatosMascotaMouseClicked

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // Llamar al método agregar de la clase ControladorMascotas para guardar una nueva mascota
        ControladorMascotas controlador = new ControladorMascotas(this);
        controlador.agregar();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // Llamar al método editar de la clase ControladorMascotas para actualizar los datos de la mascota seleccionada
        ControladorMascotas controlador = new ControladorMascotas(this);
        controlador.editar();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnRefrescarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefrescarActionPerformed
        // Refrescar la tabla para mostrar los datos actualizados
        ControladorMascotas controlador = new ControladorMascotas(this);
        controlador.listar(tableDatosMascota);
    }//GEN-LAST:event_btnRefrescarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // Llamar al método eliminar de la clase ControladorMascotas para eliminar la mascota seleccionada
        ControladorMascotas controlador = new ControladorMascotas(this);
        controlador.eliminar();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
       char c = evt.getKeyChar();
    
    // Verifica si el carácter no es una letra
    if (!Character.isLetter(c)) {
        evt.consume(); // Ignora el carácter si no es letra
    }
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtEspecieKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEspecieKeyTyped
        char c = evt.getKeyChar();
    
    // Verifica si el carácter no es una letra
    if (!Character.isLetter(c)) {
        evt.consume(); // Ignora el carácter si no es letra
    }
    }//GEN-LAST:event_txtEspecieKeyTyped

    private void jtxtCaracteristicasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtCaracteristicasKeyTyped
            char c = evt.getKeyChar();
    
    // Verifica si el carácter no es una letra
    if (!Character.isLetter(c)) {
        evt.consume(); // Ignora el carácter si no es letra
    }
    }//GEN-LAST:event_jtxtCaracteristicasKeyTyped

    private void txtRazaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRazaKeyTyped
     char c = evt.getKeyChar();
    
    // Verifica si el carácter no es una letra
    if (!Character.isLetter(c)) {
        evt.consume(); // Ignora el carácter si no es letra
    }
    }//GEN-LAST:event_txtRazaKeyTyped

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanelBotonesMasc;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnRefrescar;
    private javax.swing.JComboBox<String> cboxCastrado;
    private javax.swing.JComboBox<String> cboxSexo;
    private com.toedter.calendar.JDateChooser dateNacimiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jtxtCaracteristicas;
    private javax.swing.JLabel lblCastrado;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblEspecie;
    private javax.swing.JLabel lblFechaNac;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblPeso;
    private javax.swing.JLabel lblPropietario1;
    private javax.swing.JLabel lblRaza;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JPanel panelMascota;
    private javax.swing.JTable tableDatosMascota;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtEspecie;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumPropietario;
    private javax.swing.JTextField txtPeso;
    private javax.swing.JTextField txtPropietario;
    private javax.swing.JTextField txtRaza;
    // End of variables declaration//GEN-END:variables
}
